version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=vasya
      - POSTGRES_PASSWORD=qwerty123